#!/bin/sh

touch /usr/src/app/karmabot.tmp

cat <<EOF > /usr/src/app/karmabot.tmp 
#!/usr/local/bin/ruby

require 'slack-ruby-client'
require 'json'

# Initialize time and karma values
time = Time.now.to_i
rk = 0
pk = 0

Slack.configure { |config| config.token = "$TOKEN" }
client = Slack::Web::Client.new
loop {
  # Only send Karma if values are above or below random values.
  if rk.to_i < rand(500..1000)
    client.chat_postMessage(channel: "$CHANNEL", text: "ruby++", as_user: true);
  else
    client.chat_postMessage(channel: "$CHANNEL", text: "How much karma does ruby have?", as_user: true);
  end
  if pk.to_i > rand(-1000..-500)
    client.chat_postMessage(channel: "$CHANNEL", text: "perl--", as_user: true);
  else
    client.chat_postMessage(channel: "$CHANNEL", text: "How much karma does perl have?", as_user: true);
  end
  sleep 1
  # Get messages and parse.
  a = client.conversations_history(channel: "$CHANNEL", inclusive: true, oldest: time).to_json;
  msg = JSON.parse(a)['messages'].reverse
  msg.each do |t|
    e = t['ts'].to_i
    ts = Time.at(e)
    if t['username'].nil?
      u = "Me"
    else
      u = t['username']
    end
    puts "#{ts} #{u}: #{t['text']}"
    # Try and get current karma value.
    if u != "Me"
      if "#{t['text']}".include? "ruby now"
        txt = "#{t['text']}".split(' ')
        rk = txt[4]
      end
      if "#{t['text']}".include? "(poo) now"
          txt = "#{t['text']}".split(' ')
          pk = txt[4]
      end
      if "#{t['text']}".include? "ruby has"
        txt = "#{t['text']}".split(' ')
        rk = txt[3]
      end
      if "#{t['text']}".include? "(poo) has"
          txt = "#{t['text']}".split(' ')
          pk = txt[3]
      end
    end
  end
  client.im_mark(channel: "$CHANNEL", ts: time)
  time = Time.now.to_i
  ts = Time.at(time)
  nap = (rand(300..1200))
  puts "#{ts} Sleeping for #{nap} seconds."
  sleep nap
}
EOF

chmod +x /usr/src/app/karmabot.tmp
mv /usr/src/app/karmabot /usr/src/app/karmabot_installer
mv /usr/src/app/karmabot.tmp /usr/src/app/karmabot

/usr/src/app/karmabot
